# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mig.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import pymysql
import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 517)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 50, 928, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 0, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.in_lname = QtWidgets.QTextEdit(self.layoutWidget)
        self.in_lname.setObjectName("in_lname")
        self.gridLayout_6.addWidget(self.in_lname, 0, 4, 1, 1)
        self.in_com = QtWidgets.QTextEdit(self.layoutWidget)
        self.in_com.setObjectName("in_com")
        self.gridLayout_6.addWidget(self.in_com, 0, 6, 1, 1)
        self.in_uname = QtWidgets.QTextEdit(self.layoutWidget)
        self.in_uname.setObjectName("in_uname")
        self.gridLayout_6.addWidget(self.in_uname, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 0, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 0, 5, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.com1_all = QtWidgets.QLineEdit(self.layoutWidget)
        self.com1_all.setObjectName("com1_all")
        self.gridLayout.addWidget(self.com1_all, 0, 1, 1, 1)
        self.com1_out = QtWidgets.QLineEdit(self.layoutWidget)
        self.com1_out.setObjectName("com1_out")
        self.gridLayout.addWidget(self.com1_out, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.com1_remain = QtWidgets.QLineEdit(self.layoutWidget)
        self.com1_remain.setObjectName("com1_remain")
        self.gridLayout.addWidget(self.com1_remain, 3, 1, 1, 1)
        self.com1_in = QtWidgets.QLineEdit(self.layoutWidget)
        self.com1_in.setObjectName("com1_in")
        self.gridLayout.addWidget(self.com1_in, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.com2_all = QtWidgets.QLineEdit(self.layoutWidget)
        self.com2_all.setObjectName("com2_all")
        self.gridLayout_2.addWidget(self.com2_all, 0, 1, 1, 1)
        self.com2_out = QtWidgets.QLineEdit(self.layoutWidget)
        self.com2_out.setObjectName("com2_out")
        self.gridLayout_2.addWidget(self.com2_out, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.com2_remain = QtWidgets.QLineEdit(self.layoutWidget)
        self.com2_remain.setObjectName("com2_remain")
        self.gridLayout_2.addWidget(self.com2_remain, 3, 1, 1, 1)
        self.com2_in = QtWidgets.QLineEdit(self.layoutWidget)
        self.com2_in.setObjectName("com2_in")
        self.gridLayout_2.addWidget(self.com2_in, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 0, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.com3_all = QtWidgets.QLineEdit(self.layoutWidget)
        self.com3_all.setObjectName("com3_all")
        self.gridLayout_4.addWidget(self.com3_all, 0, 1, 1, 1)
        self.com3_out = QtWidgets.QLineEdit(self.layoutWidget)
        self.com3_out.setObjectName("com3_out")
        self.gridLayout_4.addWidget(self.com3_out, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
        self.com3_remain = QtWidgets.QLineEdit(self.layoutWidget)
        self.com3_remain.setObjectName("com3_remain")
        self.gridLayout_4.addWidget(self.com3_remain, 3, 1, 1, 1)
        self.com3_in = QtWidgets.QLineEdit(self.layoutWidget)
        self.com3_in.setObjectName("com3_in")
        self.gridLayout_4.addWidget(self.com3_in, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 2, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 3, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 0, 0, 1, 1)
        self.out_uname = QtWidgets.QTextEdit(self.layoutWidget)
        self.out_uname.setObjectName("out_uname")
        self.gridLayout_7.addWidget(self.out_uname, 0, 2, 1, 1)
        self.out_lname = QtWidgets.QTextEdit(self.layoutWidget)
        self.out_lname.setObjectName("out_lname")
        self.gridLayout_7.addWidget(self.out_lname, 0, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_7.addWidget(self.pushButton_2, 0, 7, 1, 1)
        self.out_com = QtWidgets.QTextEdit(self.layoutWidget)
        self.out_com.setObjectName("out_com")
        self.gridLayout_7.addWidget(self.out_com, 0, 6, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 5, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 4, 0, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 50, 12, 12))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Check_Cadet"))
        self.label_26.setText(_translate("MainWindow", "กองพันที่ 1"))
        self.in_lname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_com.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                       "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                       "p, li { white-space: pre-wrap; }\n"
                                       "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                       "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                       "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.in_uname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "IN"))
        self.label_16.setText(_translate("MainWindow", "เข้ากองพัน"))
        self.label_17.setText(_translate("MainWindow", "ชื่อ"))
        self.label_18.setText(_translate("MainWindow", "นามสกุล"))
        self.label_19.setText(_translate("MainWindow", "กองร้อย"))
        self.label.setText(_translate("MainWindow", "1st Company"))
        self.label_2.setText(_translate("MainWindow", "ยอดเดิม"))
        self.label_3.setText(_translate("MainWindow", "เข้ากองพัน"))
        self.label_4.setText(_translate("MainWindow", "นอกกองพัน"))
        self.label_8.setText(_translate("MainWindow", "คงเหลือ"))
        self.label_5.setText(_translate("MainWindow", "2nd Company"))
        self.label_6.setText(_translate("MainWindow", "ยอดเดิม"))
        self.label_7.setText(_translate("MainWindow", "เข้ากองพัน"))
        self.label_9.setText(_translate("MainWindow", "นอกกองพัน"))
        self.label_10.setText(_translate("MainWindow", "คงเหลือ"))
        self.label_11.setText(_translate("MainWindow", "3rd Company"))
        self.label_12.setText(_translate("MainWindow", "ยอดเดิม"))
        self.label_13.setText(_translate("MainWindow", "เข้ากองพัน"))
        self.label_14.setText(_translate("MainWindow", "นอกกองพัน"))
        self.label_15.setText(_translate("MainWindow", "คงเหลือ"))
        self.label_25.setText(_translate("MainWindow", "ออกกองพัน"))
        self.out_uname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                          "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.out_lname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                          "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                          "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "OUT"))
        self.out_com.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "นามสกุล"))
        self.label_20.setText(_translate("MainWindow", "ชื่อ"))
        self.label_22.setText(_translate("MainWindow", "กองร้อย"))

        # Insert
        self.pushButton.clicked.connect(self.dumpall)

        # UPDATE
        self.pushButton_2.clicked.connect(self.outschool)

        # Show data Company 1
        self.com1_all.setPlaceholderText(com1all())
        self.com1_in.setPlaceholderText(com1stay())
        self.com1_out.setPlaceholderText(com1out())
        self.com1_remain.setPlaceholderText(com1remain())

        # Show data Company 2
        self.com2_all.setPlaceholderText(com2all())
        self.com2_in.setPlaceholderText(com2stay())
        self.com2_out.setPlaceholderText(com2out())
        self.com2_remain.setPlaceholderText(com2remain())

        # Show data Company 3
        self.com3_all.setPlaceholderText(com3all())
        self.com3_in.setPlaceholderText(com3stay())
        self.com3_out.setPlaceholderText(com3out())
        self.com3_remain.setPlaceholderText(com3remain())


# .............................................................
# .............................................................
# .............................................................
# .............................................................
# ...........................................................
# ----- Function GUI && Database

# Insert Done

    def insertdata(self):
        print("Hello")
        uname = self.in_uname.toPlainText()
        lname = self.in_lname.toPlainText()
        com = self.in_com.toPlainText()
        print(uname + "" + lname + com)
        insert_inbatt(uname, lname, com)

    def dumpall(self):
        print("dump")
        uname = self.in_uname.toPlainText()
        lname = self.in_lname.toPlainText()
        com = self.in_com.toPlainText()
        dump(uname, lname, com)
        # Show data Company 1
        self.com1_all.setPlaceholderText(com1all())
        self.com1_in.setPlaceholderText(com1stay())
        self.com1_out.setPlaceholderText(com1out())
        self.com1_remain.setPlaceholderText(com1remain())

        # Show data Company 2
        self.com2_all.setPlaceholderText(com2all())
        self.com2_in.setPlaceholderText(com2stay())
        self.com2_out.setPlaceholderText(com2out())
        self.com2_remain.setPlaceholderText(com2remain())

        # Show data Company 3
        self.com3_all.setPlaceholderText(com3all())
        self.com3_in.setPlaceholderText(com3stay())
        self.com3_out.setPlaceholderText(com3out())
        self.com3_remain.setPlaceholderText(com3remain())

    def backschool(self):
        print("into")
        uname = self.in_uname.toPlainText()
        lname = self.in_lname.toPlainText()
        com = self.in_com.toPlainText()
        print(uname+""+lname+com)
        inbatt(lname)

    def outschool(self):
        print("out")
        uname = self.out_uname.toPlainText()
        lname = self.out_lname.toPlainText()
        com = self.out_com.toPlainText()
        print(uname+""+lname+com)
        outbatt(lname)
        # Show data Company 1
        self.com1_all.setPlaceholderText(com1all())
        self.com1_in.setPlaceholderText(com1stay())
        self.com1_out.setPlaceholderText(com1out())
        self.com1_remain.setPlaceholderText(com1remain())

        # Show data Company 2
        self.com2_all.setPlaceholderText(com2all())
        self.com2_in.setPlaceholderText(com2stay())
        self.com2_out.setPlaceholderText(com2out())
        self.com2_remain.setPlaceholderText(com2remain())

        # Show data Company 3
        self.com3_all.setPlaceholderText(com3all())
        self.com3_in.setPlaceholderText(com3stay())
        self.com3_out.setPlaceholderText(com3out())
        self.com3_remain.setPlaceholderText(com3remain())


# ----- Connect to Database
def ConnectorMysql():
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        passwd="",
        database="check_cadet",
        # auth_plugin='mysql_native_password'
    )
    print('Connect Database Successful')
    return mydb


def dump(uname, lname, com):
    print(uname, lname, com)
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT * FROM batt WHERE lname="{lname}"'
    print("dump databasesuccess!!")
    print(sql)
    cur.execute(sql)
    myresult = cur.fetchall()

    print(myresult)
    if len(myresult) != 0:
        print("send to inbatt fn")
        inbatt(lname)
    else:
        print("send to insert fn")
        insert_inbatt(lname, uname, com)


def inbatt(lname):
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'UPDATE `batt` SET `stay`=1,`outc`=0 WHERE lname="{lname}"'
    print("Check in success!!")
    cur.execute(sql)
    db.commit()
    db.close()

# Insert Done


def insert_inbatt(lname, uname, com):
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'INSERT INTO `batt`(`lname`, `uname`, `stay`, `outc`, `com`) VALUES ("{lname}","{uname}",1,0,{com})'
    print(sql)
    print("Insert into success!!")
    cur.execute(sql)
    db.commit()
    db.close()


def outbatt(lname):
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'UPDATE `batt` SET `stay`=0,`outc`=1 WHERE lname="{lname}"'
    print(sql)
    print("Check out success!!")
    cur.execute(sql)
    db.commit()
    db.close()


def com1all():
    print("com1 all")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay+outc) FROM `batt` WHERE com=1'
    print("com1_all success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com1stay():
    print("com1 stay")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=1'
    print("com1_stay success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com1out():
    print("com1 out")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(outc) FROM `batt` WHERE com=1'
    print("com1_out success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com1remain():
    print("com1 remain")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=1'
    print("com1_remain success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com2all():
    print("com2 all")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay+outc) FROM `batt` WHERE com=2'
    print("com2_all success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com2stay():
    print("com2 stay")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=2'
    print("com2_stay success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com2out():
    print("com2 out")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(outc) FROM `batt` WHERE com=2'
    print("com2_out success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com2remain():
    print("com2 remain")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=2'
    print("com2_remain success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com3all():
    print("com3 all")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay+outc) FROM `batt` WHERE com=3'
    print("com3_all success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com3stay():
    print("com3 stay")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=3'
    print("com3_stay success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com3out():
    print("com3 out")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(outc) FROM `batt` WHERE com=3'
    print("com3_out success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com3remain():
    print("com3 remain")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=3'
    print("com3_remain success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
