# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\EP\Mig\UI\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from inbatt import Ui_InbattWindow
from outbatt import Ui_OutbattWindow
from show import Ui_ShowWindow


class Ui_MenwWindow(object):
    def openinbatt(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_InbattWindow()
        self.ui.setupUi(self.window)
        # MainWindow.hide()
        self.window.show()
        

    def openoutbatt(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_OutbattWindow()
        self.ui.setupUi(self.window)
        # MainWindow.hide()
        self.window.show()
 

    def openshowbatt(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ShowWindow()
        self.ui.setupUi(self.window)
        # MainWindow.hide()
        self.window.show()    
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(446, 378)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.448864, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(131, 22, 190, 294))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.668342 rgba(255, 255, 0, 255));")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.button_inbatt = QtWidgets.QPushButton(self.widget)
        self.button_inbatt.setStyleSheet("\n"
"background-color: rgb(255, 255, 0);")
        self.button_inbatt.setObjectName("button_inbatt")
        self.gridLayout.addWidget(self.button_inbatt, 2, 0, 1, 1)
        
        self.button_inbatt.clicked.connect(self.openinbatt)
          
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.button_outbatt = QtWidgets.QPushButton(self.widget)
        self.button_outbatt.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.button_outbatt.setObjectName("button_outbatt")
        self.gridLayout.addWidget(self.button_outbatt, 4, 0, 1, 1)
        
        self.button_outbatt.clicked.connect(self.openoutbatt)

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.button_show = QtWidgets.QPushButton(self.widget)
        self.button_show.setStyleSheet("\n"
"background-color: rgb(255, 255, 0);")
        self.button_show.setObjectName("button_show")
        self.gridLayout.addWidget(self.button_show, 6, 0, 1, 1)
        
        self.button_show.clicked.connect(self.openshowbatt)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 446, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "1 st Battalion"))
        self.button_inbatt.setText(_translate("MainWindow", "เข้ากองพัน"))
        self.button_outbatt.setText(_translate("MainWindow", "ออกกองพัน"))
        self.button_show.setText(_translate("MainWindow", "แสดงยอด"))
      

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MenwWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
