# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\EP\Mig\UI\show.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_ShowWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 306)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.668342 rgba(255, 255, 0, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 30, 531, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 0, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_4.addWidget(self.lineEdit_13, 0, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_4.addWidget(self.lineEdit_14, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 3, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_4.addWidget(self.lineEdit_15, 3, 1, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_4.addWidget(self.lineEdit_16, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 0, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_3.addWidget(self.lineEdit_9, 0, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_3.addWidget(self.lineEdit_10, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 3, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 0, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_26.setText(_translate("MainWindow", "กองพันที่ 1"))
        self.label_15.setText(_translate("MainWindow", "3rd Company"))
        self.label_16.setText(_translate("MainWindow", "ยอดเดิม"))
        self.label_17.setText(_translate("MainWindow", "เข้ากองพัน"))
        self.label_18.setText(_translate("MainWindow", "นอกกองพัน"))
        self.label_19.setText(_translate("MainWindow", "คงเหลือ"))
        self.label.setText(_translate("MainWindow", "1st Company"))
        self.label_8.setText(_translate("MainWindow", "คงเหลือ"))
        self.label_4.setText(_translate("MainWindow", "นอกกองพัน"))
        self.label_2.setText(_translate("MainWindow", "ยอดเดิม"))
        self.label_3.setText(_translate("MainWindow", "เข้ากองพัน"))
        self.label_5.setText(_translate("MainWindow", "2nd Company"))
        self.label_11.setText(_translate("MainWindow", "ยอดเดิม"))
        self.label_12.setText(_translate("MainWindow", "เข้ากองพัน"))
        self.label_13.setText(_translate("MainWindow", "นอกกองพัน"))
        self.label_14.setText(_translate("MainWindow", "คงเหลือ"))
        
          
        # Show data Company 1
        self.lineEdit.setPlaceholderText(com1all())
        self.lineEdit_2.setPlaceholderText(com1stay())
        self.lineEdit_3.setPlaceholderText(com1out())
        self.lineEdit_7.setPlaceholderText(com1remain())

        # Show data Company 2
        self.lineEdit_9.setPlaceholderText(com2all())
        self.lineEdit_12.setPlaceholderText(com2stay())
        self.lineEdit_10.setPlaceholderText(com2out())
        self.lineEdit_11.setPlaceholderText(com2remain())

        # Show data Company 3
        self.lineEdit_13.setPlaceholderText(com3all())
        self.lineEdit_16.setPlaceholderText(com3stay())
        self.lineEdit_14.setPlaceholderText(com3out())
        self.lineEdit_15.setPlaceholderText(com3remain())

def ConnectorMysql():
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        passwd="",
        database="check_cadet",
        # auth_plugin='mysql_native_password'
    )
    print('Connect Database Successful')
    return mydb

def com1all():
    print("com1 all")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay+outc) FROM `batt` WHERE com=1'
    print("com1_all success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com1stay():
    print("com1 stay")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=1'
    print("com1_stay success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com1out():
    print("com1 out")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(outc) FROM `batt` WHERE com=1'
    print("com1_out success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com1remain():
    print("com1 remain")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=1'
    print("com1_remain success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com2all():
    print("com2 all")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay+outc) FROM `batt` WHERE com=2'
    print("com2_all success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com2stay():
    print("com2 stay")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=2'
    print("com2_stay success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com2out():
    print("com2 out")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(outc) FROM `batt` WHERE com=2'
    print("com2_out success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com2remain():
    print("com2 remain")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=2'
    print("com2_remain success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com3all():
    print("com3 all")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay+outc) FROM `batt` WHERE com=3'
    print("com3_all success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com3stay():
    print("com3 stay")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=3'
    print("com3_stay success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com3out():
    print("com3 out")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(outc) FROM `batt` WHERE com=3'
    print("com3_out success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


def com3remain():
    print("com3 remain")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=3'
    print("com3_remain success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ShowWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
