# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\EP\Mig\UI\inbatt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_InbattWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(272, 286)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.668342 rgba(255, 255, 0, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 246, 251))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.in_head = QtWidgets.QLabel(self.widget)
        self.in_head.setObjectName("in_head")
        self.gridLayout.addWidget(self.in_head, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.in_name = QtWidgets.QLineEdit(self.widget)
        self.in_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.in_name.setObjectName("in_name")
        self.gridLayout.addWidget(self.in_name, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.in_lname = QtWidgets.QLineEdit(self.widget)
        self.in_lname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.in_lname.setObjectName("in_lname")
        self.gridLayout.addWidget(self.in_lname, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.in_com = QtWidgets.QLineEdit(self.widget)
        self.in_com.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.in_com.setObjectName("in_com")
        self.gridLayout.addWidget(self.in_com, 6, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 7, 0, 1, 2)
        self.inbutton = QtWidgets.QPushButton(self.widget)
        self.inbutton.setObjectName("in")
        self.gridLayout.addWidget(self.inbutton, 8, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.in_head.setText(_translate("MainWindow", "เข้ากองพัน"))
        self.label.setText(_translate("MainWindow", "ชื่อ :"))
        self.label_2.setText(_translate("MainWindow", "นามสกุล :"))
        self.label_3.setText(_translate("MainWindow", "กองร้อย :"))
        self.inbutton.setText(_translate("MainWindow", "ลงชื่อเข้ากองพัน"))
        
        self.inbutton.clicked.connect(self.dumpall)
        
    def dumpall(self):
        print("dump")
        uname = self.in_name.text()
        lname = self.in_lname.text()
        com = self.in_com.text()
        dump(uname,lname,com)
 
def ConnectorMysql():
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        passwd="12341234",
        database="checkcadet",
        # auth_plugin='mysql_native_password'
    )
    print('Connect Database Successful')
    return mydb

def dump(uname,lname,com):
    print(uname,lname,com)
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT * FROM batt WHERE lname="{lname}"'
    print("dump databasesuccess!!")
    print(sql)
    cur.execute(sql)
    myresult = cur.fetchall()

    print(myresult)
    
    if myresult != []:
        print("send to inbatt fn")
        inbatt(lname)
    else:
        print("send to insert fn")
        insert_inbatt(lname, uname, com)
        
def inbatt(lname):
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'UPDATE `batt` SET `stay`=1,`outc`=0 WHERE lname="{lname}"'
    print("Check in success!!")
    cur.execute(sql)
    db.commit()
    db.close()
            
def insert_inbatt(lname, uname, com):
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'INSERT INTO `batt`(`lname`, `uname`, `stay`, `outc`, `com`) VALUES ("{lname}","{uname}",1,0,{com})'
    print(sql)
    print("Insert into success!!")
    cur.execute(sql)
    db.commit()
    db.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_InbattWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
